#!/usr/bin/env bun
/**
 * Vendor the Matt Pocock skill set into this fork so `main` ships it by default.
 *
 *   bun run vendor-skills                    use the default source checkout
 *   bun run vendor-skills --source <path>    vendor from another checkout
 *
 * Rewrites `skills/` from scratch: every file under it is generated, so nothing
 * there should be hand-edited. `sync-upstream` installs the result into
 * `~/.config/opencode/skills/`, which is where the running binary discovers
 * skills (packages/opencode/src/skill/index.ts OPENCODE_SKILL_PATTERN).
 */
import { $ } from "bun"
import path from "path"
import { cp, mkdir, readdir, rm, writeFile } from "fs/promises"

const ROOT = path.resolve(import.meta.dirname, "..")
const DEST = path.join(ROOT, "skills")
const DEFAULT_SOURCE = "/home/eric/Documents/Development/private/agent-design/tools/mattpocock"

// The upstream repo promotes engineering + productivity only. `misc` and
// `deprecated` are retired or rarely used, and `in-progress` is explicitly
// public-for-feedback; scripts/link-skills.sh skips the first two.
const BUCKETS = ["engineering", "productivity"] as const

// `agents/openai.yaml` is upstream's Codex-plugin manifest. opencode never
// reads it, and the skill tool caps the resource list it shows the model
// (packages/opencode/src/tool/skill.ts limit: 10), so shipping it would spend
// a slot on a file that cannot be used. Bucket READMEs index upstream's own
// docs site and describe skills we do not vendor.
const EXCLUDED = new Set(["agents/openai.yaml", "README.md"])

const sourceArg = process.argv.indexOf("--source")
const source =
  sourceArg === -1
    ? (process.env.MATTPOCOCK_SKILLS ?? DEFAULT_SOURCE)
    : path.resolve(process.argv[sourceArg + 1] ?? DEFAULT_SOURCE)

const revision = (await $`git -C ${source} rev-parse HEAD`.quiet()).text().trim()
const branch = (await $`git -C ${source} rev-parse --abbrev-ref HEAD`.quiet()).text().trim()
if (!revision) throw new Error(`not a git checkout, or empty: ${source}`)

await rm(DEST, { recursive: true, force: true })
await mkdir(DEST, { recursive: true })

const vendored: { skill: string; files: string[] }[] = []
for (const bucket of BUCKETS) {
  for (const dir of await readdirSorted(path.join(source, "skills", bucket))) {
    const skillRoot = path.join(source, "skills", bucket, dir)
    if (!(await Bun.file(path.join(skillRoot, "SKILL.md")).exists())) continue

    const files = (await Array.fromAsync(new Bun.Glob("**/*").scan(skillRoot)))
      .map((file) => file.replaceAll("\\", "/"))
      .filter((file) => !EXCLUDED.has(file))
      .sort()

    for (const file of files) {
      const target = path.join(DEST, dir, file)
      await mkdir(path.dirname(target), { recursive: true })
      await cp(path.join(skillRoot, file), target)
    }
    vendored.push({ skill: dir, files })
  }
}

if (vendored.length === 0) throw new Error(`no skills found under ${source}/skills`)

// MIT requires the copyright and permission notice to travel with the work.
// `bun build --compile` strips comments and ships only `dist/<name>/bin/*`, so
// the notice is vendored as data next to the skills rather than as a comment.
await cp(path.join(source, "LICENSE"), path.join(DEST, "LICENSE"))

const totalFiles = vendored.reduce((sum, skill) => sum + skill.files.length, 0)
await writeFile(
  path.join(DEST, "PROVENANCE.md"),
  [
    "# Vendored skills",
    "",
    "Generated by `bun run vendor-skills`. Do not hand-edit; re-run the script.",
    "",
    `- Source: mattpocock/skills (${source})`,
    `- Revision: \`${revision}\` (${branch})`,
    `- Vendored: ${new Date().toISOString().slice(0, 10)}`,
    `- Buckets: ${BUCKETS.join(", ")}`,
    `- Skills: ${vendored.length}, files: ${totalFiles}`,
    `- Excluded: ${[...EXCLUDED].join(", ")}`,
    `- License: MIT, see [LICENSE](LICENSE) (Copyright (c) 2026 Matt Pocock)`,
    "",
    "`sync-upstream` copies this tree to `~/.config/opencode/skills/`, where the",
    "running binary discovers it. A skill of the same name placed there by hand",
    "overrides nothing: this tree is installed over it, so keep local edits in a",
    "differently named skill or re-vendor.",
    "",
    "| Skill | Files |",
    "| --- | --- |",
    ...vendored
      .toSorted((a, b) => a.skill.localeCompare(b.skill))
      .map((skill) => `| \`${skill.skill}\` | ${skill.files.length} |`),
    "",
  ].join("\n"),
)

console.log(`vendored ${vendored.length} skills (${totalFiles} files) from ${revision.slice(0, 9)}`)

async function readdirSorted(dir: string) {
  return (await readdir(dir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .toSorted()
}
